const translations = {
    en: {
        title: "QR Code Generator",
        contentLabel: "Content:",
        placeholder: "Enter your content here to make QR Code",
        errorMessage: "Please enter content to generate or clear QR code.",
        generateBtn: "Generate QR",
        clearBtn: "Clear this QR",
        historyBtn: "Show History",
        customizationBtn: "Advanced Customization",
        toggleThemeBtn: "Toggle Theme",
        downloadBtn: "Download QR Code",
        titleQRHistory: "QR Code History",
        historyTableQRCode: "QR Code",
        historyTableQRContent: "Content",
        historyTableQRTimestamp: "Timestamp",
        historyTableQRAction: "Action",
        titleCustomizationDialog: "Advanced Customization",
        customizationDialogSetting1: "QR Lines/Dots Color:",
        customizationDialogSetting2: "QR Background Color:",
        customizationDialogSetting3: "Dot Scale (0.1 - 1):",
        customizationDialogSetting4: "Logo:",
        customizationDialogSetting4B1: "Clear logo",
        customizationDialogSetting5: "Background Image:",
        customizationDialogSetting5B1: "Clear background image",
        customizationDialogSetting6: "Auto Color (check for auto):",
        customizationDialogSetting7: "Size:",
        customizationDialogSetting8: "Margin:",
        customizationDialogSetting9: "Error Correction Level:",
        customizationDialogSetting10: "Title:",
        customizationDialogSetting11: "Subtitle:",
        customizationDialogSetting12: "Binary:",
        customizationDialogSetting13: "Tooltip:",
        customizationDialogSetting14: "Drawer:",
        customizationDialogSetting15: "UTF-8 Without BOM:",
        customizationDialogSetting16: "Logo Width:",
        customizationDialogSetting17: "Logo Height:",
        customizationDialogSetting18: "Logo Max Width:",
        customizationDialogSetting19: "Logo Max Height:",
        customizationDialogSetting20: "Logo Background Color:",
        customizationDialogSetting21: "Logo Background Transparent:",
        customizationDialogSetting22: "Background Image Alpha:",
        customizationDialogSetting23: "Auto Color Dark:",
        customizationDialogSetting24: "Auto Color Light:",
        customizationDialogSetting25: "PO:",
        customizationDialogSetting26: "PI:",
        customizationDialogSetting27: "PO_TL:",
        customizationDialogSetting28: "PI_TL:",
        customizationDialogSetting29: "PO_TR:",
        customizationDialogSetting30: "PI_TR:",
        customizationDialogSetting31: "PO_BL:",
        customizationDialogSetting32: "PI_BL:",
        customizationDialogSetting33: "AO:",
        customizationDialogSetting34: "AI:",
        customizationDialogSetting35: "Timing:",
        customizationDialogSetting36: "Timing H:",
        customizationDialogSetting37: "Timing V:",
        customizationDialogSetting38: "Title Font:",
        customizationDialogSetting39: "Title Color:",
        customizationDialogSetting40: "Title Background Color:",
        customizationDialogSetting41: "Title Height:",
        customizationDialogSetting42: "Title Top:",
        customizationDialogSetting43: "Subtitle Font:",
        customizationDialogSetting44: "Subtitle Color:",
        customizationDialogSetting45: "Subtitle Top:",
        customizationDialogSetting46: "Drawer:",
        customizationDialogSetting47: "UTF-8 Without BOM:",
        customizationDialogSetting48: "UTF-8 Without BOM:",
        customizationDialogSetting49: "UTF-8 Without BOM:",
        qrErrorCorrectionLevel1: "Low (7%)",
        qrErrorCorrectionLevel2: "Medium (15%)",
        qrErrorCorrectionLevel3: "Quartile (25%)",
        qrErrorCorrectionLevel4: "High (30%)",
        historyDialogNote1L1: "Note: QR Code history will be deleted in 30 days.",
        historyDialogNote1L2: "Wipe it now.",
    },
    es: {
        title: "Generador de Código QR",
        contentLabel: "Contenido:",
        placeholder: "Ingrese su contenido aquí para crear un Código QR",
        errorMessage: "Por favor, ingrese contenido para generar o borrar el código QR.",
        generateBtn: "Generar QR",
        clearBtn: "Borrar este QR",
        historyBtn: "Mostrar Historial",
        customizationBtn: "Personalización Avanzada",
        toggleThemeBtn: "Cambiar Tema",
        downloadBtn: "Descargar Código QR",
        titleQRHistory: "Historial de códigos QR",
        historyTableQRCode: "Código QR",
        historyTableQRContent: "Contenido",
        historyTableQRTimestamp: "Marca de tiempo",
        historyTableQRAction: "Acción",
        titleCustomizationDialog: "Personalización Avanzada",
        customizationDialogSetting1: "Color de Líneas/Puntos QR:",
        customizationDialogSetting2: "Color de Fondo QR:",
        customizationDialogSetting3: "Escala de Puntos (0.1 - 1):",
        customizationDialogSetting4: "Logo:",
        customizationDialogSetting4B1: "Borrar logo",
        customizationDialogSetting5: "Imagen de Fondo:",
        customizationDialogSetting5B1: "Borrar imagen de fondo",
        customizationDialogSetting6: "Color Automático (marque para auto):",
        customizationDialogSetting7: "Tamaño:",
        customizationDialogSetting8: "Margen:",
        customizationDialogSetting9: "Nivel de Corrección de Error:",
        qrErrorCorrectionLevel1: "Bajo (7%)",
        qrErrorCorrectionLevel2: "Medio (15%)",
        qrErrorCorrectionLevel3: "Cuartil (25%)",
        qrErrorCorrectionLevel4: "Alto (30%)",
        historyDialogNote1L1: "Nota: El historial de códigos QR se eliminará en 30 días.",
        historyDialogNote1L2: "Borrarlo ahora."
    },
    fr: {
        title: "Générateur de Code QR",
        contentLabel: "Contenu:",
        placeholder: "Entrez votre contenu ici pour créer un Code QR",
        errorMessage: "Veuillez entrer du contenu pour générer ou effacer le code QR.",
        generateBtn: "Générer QR",
        clearBtn: "Effacer ce QR",
        historyBtn: "Afficher l'Historique",
        customizationBtn: "Personnalisation Avancée",
        toggleThemeBtn: "Changer le Thème",
        downloadBtn: "Télécharger le code QR",
        titleQRHistory: "Historique des Codes QR",
        historyTableQRCode: "Code QR",
        historyTableQRContent: "Contenu",
        historyTableQRTimestamp: "Horodatage",
        historyTableQRAction: "Action",
        titleCustomizationDialog: "Personnalisation Avancée",
        customizationDialogSetting1: "Couleur des Lignes/Points QR:",
        customizationDialogSetting2: "Couleur de Fond QR:",
        customizationDialogSetting3: "Échelle de Points (0.1 - 1):",
        customizationDialogSetting4: "Logo:",
        customizationDialogSetting4B1: "Effacer le logo",
        customizationDialogSetting5: "Image de Fond:",
        customizationDialogSetting5B1: "Effacer l'image de fond",
        customizationDialogSetting6: "Couleur Automatique (cochez pour auto):",
        customizationDialogSetting7: "Taille:",
        customizationDialogSetting8: "Marge:",
        customizationDialogSetting9: "Niveau de Correction d'Erreur:",
        qrErrorCorrectionLevel1: "Faible (7%)",
        qrErrorCorrectionLevel2: "Moyen (15%)",
        qrErrorCorrectionLevel3: "Quartile (25%)",
        qrErrorCorrectionLevel4: "Élevé (30%)",
        historyDialogNote1L1: "Remarque: L'historique des codes QR sera supprimé dans 30 jours.",
        historyDialogNote1L2: "L'effacer maintenant.",
    },
    vi: {
        title: "Trình Tạo Mã QR",
        contentLabel: "Nội dung:",
        placeholder: "Nhập nội dung của bạn vào đây để tạo Mã QR",
        errorMessage: "Vui lòng nhập nội dung để tạo hoặc xóa mã QR.",
        generateBtn: "Tạo QR",
        clearBtn: "Xóa mã QR này",
        historyBtn: "Hiển Thị Lịch Sử",
        customizationBtn: "Tùy Chỉnh Nâng Cao",
        toggleThemeBtn: "Đổi Giao Diện",
        downloadBtn: "Tải Xuống Mã QR",
        titleQRHistory: "Lịch Sử Mã QR",
        historyTableQRCode: "Mã QR",
        historyTableQRContent: "Nội dung",
        historyTableQRTimestamp: "Thời gian",
        historyTableQRAction: "Hành Động",
        titleCustomizationDialog: "Tùy Chỉnh Nâng Cao",
        customizationDialogSetting1: "Màu Nét QR:",
        customizationDialogSetting2: "Màu Nền QR:",
        customizationDialogSetting3: "Tỉ Lệ Điểm (0.1 - 1):",
        customizationDialogSetting4: "Logo:",
        customizationDialogSetting4B1: "Xóa logo",
        customizationDialogSetting5: "Hình Nền:",
        customizationDialogSetting5B1: "Xóa hình nền",
        customizationDialogSetting6: "Tự Động Màu (đánh dấu để tự động):",
        customizationDialogSetting7: "Kích Thước:",
        customizationDialogSetting8: "Lề:",
        customizationDialogSetting9: "Mức Sửa Lỗi:",
        qrErrorCorrectionLevel1: "Thấp (7%)",
        qrErrorCorrectionLevel2: "Trung Bình (15%)",
        qrErrorCorrectionLevel3: "Cao (25%)",
        qrErrorCorrectionLevel4: "Cực cao (30%)",
        historyDialogNote1L1: "Lưu ý: Lịch sử mã QR sẽ bị xóa trong 30 ngày.",
        historyDialogNote1L2: "Xoá ngay bây giờ",
    },
    zh: {
        title: "二维码生成器",
        contentLabel: "内容:",
        placeholder: "在此输入内容以创建二维码",
        errorMessage: "请输入内容以生成或清除二维码。",
        generateBtn: "生成二维码",
        clearBtn: "清除此二维码",
        historyBtn: "显示历史记录",
        customizationBtn: "高级自定义",
        toggleThemeBtn: "切换主题",
        downloadBtn: "下载二维码",
        titleQRHistory: "二维码历史记录",
        historyTableQRCode: "二维码",
        historyTableQRContent: "内容",
        historyTableQRTimestamp: "时间戳",
        historyTableQRAction: "操作",
        titleCustomizationDialog: "高级自定义",
        customizationDialogSetting1: "QR线/点颜色:",
        customizationDialogSetting2: "QR背景颜色:",
        customizationDialogSetting3: "点缩放 (0.1 - 1):",
        customizationDialogSetting4: "标志:",
        customizationDialogSetting4B1: "清除标志",
        customizationDialogSetting5: "背景图片:",
        customizationDialogSetting5B1: "清除背景图片",
        customizationDialogSetting6: "自动颜色 (勾选自动):",
        customizationDialogSetting7: "大小:",
        customizationDialogSetting8: "边距:",
        customizationDialogSetting9: "纠错级别:",
        qrErrorCorrectionLevel1: "低 (7%)",
        qrErrorCorrectionLevel2: "中 (15%)",
        qrErrorCorrectionLevel3: "四分之一 (25%)",
        qrErrorCorrectionLevel4: "高 (30%)",
        historyDialogNote1L1: "注意: 二维码历史记录将在30天内删除。",
        historyDialogNote1L2: "立即清除",

    },
    ja: {
        title: "QRコードジェネレーター",
        contentLabel: "内容:",
        placeholder: "ここに内容を入力してQRコードを作成してください",
        errorMessage: "QRコードを生成または削除するには内容を入力してください。",
        generateBtn: "QRを生成",
        clearBtn: "このQRをクリア",
        historyBtn: "履歴を表示",
        customizationBtn: "高度なカスタマイズ",
        toggleThemeBtn: "テーマを切り替える",
        downloadBtn: "QRコードをダウンロード",
        titleQRHistory: "QRコード履歴",
        historyTableQRCode: "QRコード",
        historyTableQRContent: "内容",
        historyTableQRTimestamp: "タイムスタンプ",
        historyTableQRAction: "操作",
        titleCustomizationDialog: "高度なカスタマイズ",
        customizationDialogSetting1: "QR線/点の色:",
        customizationDialogSetting2: "QR背景色:",
        customizationDialogSetting3: "点のスケール (0.1 - 1):",
        customizationDialogSetting4: "ロゴ:",
        customizationDialogSetting4B1: "ロゴをクリア",
        customizationDialogSetting5: "背景画像:",
        customizationDialogSetting5B1: "背景画像をクリア",
        customizationDialogSetting6: "自動色 (自動にチェック):",
        customizationDialogSetting7: "サイズ:",
        customizationDialogSetting8: "余白:",
        customizationDialogSetting9: "エラー訂正レベル:",
        qrErrorCorrectionLevel1: "低い (7%)",
        qrErrorCorrectionLevel2: "中 (15%)",
        qrErrorCorrectionLevel3: "四半期 (25%)",
        qrErrorCorrectionLevel4: "高い (30%)",
        historyDialogNote1L1: "注意: QRコード履歴は30日で削除されます。",
        historyDialogNote1L2: "今すぐ消去",
    }
    // Add more languages as needed
};
